# code the pipeline 
name: ML Pipeline CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn pytest flake8

      - name: Run Linting
        run: |
          flake8 .

      - name: Run Preprocessing
        run: |
          python preprocessing.py

      - name: Train Model
        run: |
          python train_model.py

      - name: Run Test Cases
        run: |
          pytest tests/test_pipeline.py

      - name: Build Docker Image
        run: |
          docker build -t my_ml_app .

      - name: Run Docker Container
        run: |
          docker run my_ml_app
