# code the pipeline 
name: ML Pipeline CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy scikit-learn pytest 

      - name: Run Preprocessing
        run: |
          python3 preprocessing.py

  train:
    runs-on: ubuntu-latest
    needs: preprocess

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy scikit-learn pytest

      - name: Train Model
        run: |
          python3 train_model.py

  test:
    runs-on: ubuntu-latest
    needs: train

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy scikit-learn pytest

      - name: Run Test Cases
        run: |
          pytest tests/test_pipeline.py

  docker-build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t my_ml_app .

  docker-run:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Docker Container
        run: |
          docker run my_ml_app
